[versions]
pluginGradle = "8.2.0"
pluginSaveArgs = "2.7.5"

simprints = "2023.2.2"

kotlin = "1.9.21"
kotlinCoroutines = "1.7.3"
koin = "3.2.2"
hilt = "2.49"

composeBom = "2023.10.01"
accompanistThemeadapterMaterial = "0.28.0"
navigation = "2.7.5"
androidDataBindingCompiler = "3.3.1"
androidxAppCompat = "1.6.1"
androidxMaterial = "1.10.0"
androidxCoreKtx = "1.12.0"
androidxRecycler = "1.3.2"
lifecycleCore = "2.5.1"
lifecycleExtensions = "2.2.0"
lifecycleViewmodelKtx = "2.6.2"

room = "2.6.1"
gson = "2.10.1"
datastorePreferences = "1.0.0"


[libraries]
simprints = { module = "com.simprints:libsimprints", version.ref = "simprints" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui"}
compose-material = { module = "androidx.compose.material:material" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation = { module = "androidx.compose.foundation:foundation"}
compose-liveData = { module = "androidx.compose.runtime:runtime-livedata"}
accompanist-themeAdapter = { module = "com.google.accompanist:accompanist-themeadapter-material", version.ref = "accompanistThemeadapterMaterial" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
dataBinding-compiler = { module = "com.android.databinding:compiler", version.ref = "androidDataBindingCompiler" }
android-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
android-material = { module = "com.google.android.material:material", version.ref = "androidxMaterial" }
android-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
android-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecycler" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

room-core = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
